# Use an official Python base image
FROM python:3.11

# Set working directory
WORKDIR /cli_model

# Copy files
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .

# Run the app with uvicorn
RUN pip install --editable .

# Default shell command; override in docker-compose
CMD ["pds"]
