POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "sufi", "password": "321pass"}
###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "sufi", "password": "321pass", "email": "test@gmail.com"}
###

GET http://127.0.0.1:8000/verify
Content-Type: application/json
Authorization: Token 5aac3b803ea550c2aba13904b6ed0355b151cdba

{}