POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "test", "password": "test123"}
###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "test1", "password": "test123", "email": "test1@gmail.com"}
###

GET http://127.0.0.1:8000/verify
Content-Type: application/json
Authorization: Token 5aac3b803ea550c2aba13904b6ed0355b151cdba

{}